### ISSUE TITLE
Building with snowpack@3.2 fails

### ISSUE THREAD

**Issue by marc136** [marc136/snowpack-plugin-elm#10]
This issue relates to #8 and #9, as the snowpack builds now fail completely instead of just copying the source files to the build folder.

```sh
$ npx snowpack@3.2.2 build

> build
> snowpack build

[15:26:51] [snowpack] ! building files...
[elm-plugin] aquiring lock to compile src/Indirect.elm
[elm-plugin] aquired lock to compile src/Indirect.elm
[elm-plugin] load { file: 'src/Indirect.elm', isDev: false, isHmrEnabled: false }
[15:26:51] [snowpack] Build Result Error: There was a problem with a file build result.
[15:26:51] [snowpack] /home/marc/code/elm/snowpack-elm-example/src/Indirect.elm - Requested content ".js" but built .elm.
[15:26:51] [snowpack] Error: /home/marc/code/elm/snowpack-elm-example/src/Indirect.elm - Requested content ".js" but built .elm.
    at FileBuilder.verifyRequestFromBuild (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:112530:19)
    at FileBuilder.getResult (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:112742:42)
    at Object.loadUrl (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:131558:51)
    at async flushFileQueue (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:131966:28)
    at async build (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:131992:5)
    at async Object.command (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:132080:9)
    at async cli (/home/marc/code/elm/snowpack-elm-example/node_modules/snowpack/lib/index.js:132389:9)
```

**Comment by marc136** [comment]
Potential fix ideas: 
- [ ] If Elm compilation fails in production builds, output an empty file instead.

**Comment by marc136** [comment]
Turns out this bugfix only needs a configuration change. See https://github.com/marc136/snowpack-template-elm/commit/1d6cf746e970453768997b81e29d08ab23931c65
